In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cus =pd.read_csv('Churn.csv')
cus.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
cus.shape

(10000, 14)

In [4]:
cus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
cus.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [6]:
cus['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
#spliting
x = cus.iloc[:, :1]
y = cus.iloc[:, 1:]

In [8]:
from sklearn.model_selection import train_test_split


X_train , X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3 , random_state =  0)
X_train , X_test, y_train, y_test

(      RowNumber
 7681       7682
 9031       9032
 3691       3692
 202         203
 5625       5626
 ...         ...
 9225       9226
 4859       4860
 3264       3265
 9845       9846
 2732       2733

 [7000 rows x 1 columns],
       RowNumber
 9394       9395
 898         899
 2398       2399
 5906       5907
 2343       2344
 ...         ...
 4004       4005
 7375       7376
 9307       9308
 8394       8395
 5233       5234

 [3000 rows x 1 columns],
       CustomerId           Surname  CreditScore Geography  Gender  Age  \
 7681    15633608             Black          641    France    Male   33
 9031    15742323            Barese          541    France    Male   39
 3691    15760244              Ives          590    France  Female   76
 202     15600974                He          516     Spain    Male   50
 5625    15663234            Bishop          508    France  Female   60
 ...          ...               ...          ...       ...     ...  ...
 9225    15584928  Ugochukwutubelum          594   Germany  Female   32
 4859    15647111             White          794     Spain  Female   22
 3264    15574372            Hoolan          738    France    Male   35
 9845    15664035           Parsons          590     Spain  Female   38
 2732    15592816          Udokamma          623   Germany  Female   48

       Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
 7681       2  146193.60              2          1               1
 9031       7       0.00              2          1               0
 3691       5  160979.68              1          0               1
 202        5       0.00              1          0               1
 5625       7  143262.04              1          1               1
 ...      ...        ...            ...        ...             ...
 9225       4  120074.97              2          1               1
 4859       4  114440.24              1          1               1
 3264       5  161274.05              2          1               0
 9845       9       0.00              2          1               1
 2732       1  108076.33              1          1               0

       EstimatedSalary  Exited
 7681         55796.83       1
 9031         19823.02       0
 3691         13848.58       0
 202         146145.93       1
 5625        129562.74       0
 ...               ...     ...
 9225        162961.79       0
 4859        107753.07       0
 3264        181429.87       0
 9845        148750.16       0
 2732        118855.26       1

 [7000 rows x 13 columns],
       CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
 9394    15615753  Upchurch          597   Germany  Female   35       8
 898     15654700   Fallaci          523    France  Female   40       2
 2398    15633877  Morrison          706     Spain  Female   42       8
 5906    15745623   Worsnop          788    France    Male   32       4
 2343    15765902    Gibson          706   Germany    Male   38       5
 ...          ...       ...          ...       ...     ...  ...     ...
 4004    15738546   Gboliwe          530     Spain  Female   41       4
 7375    15638871    Ch'ang          639    France    Male   77       6
 9307    15680405     P'eng          685    France    Male   40       2
 8394    15597983     Brown          692    France    Male   69      10
 5233    15591286   Simmons          731   Germany  Female   49       4

         Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
 9394  131101.04              1          1               1        192852.67
 898   102967.41              1          1               0        128702.10
 2398   95386.82              1          1               1         75732.25
 5906  112079.58              1          0               0         89368.59
 2343  163034.82              2          1               1        135662.17
 ...         ...            ...        ...             ...              ...
 4004       0.00              2          0               1        147606.71
 7375   80926.02              2          1               1         55829.25
 9307  168001.34              2          1               1        167400.29
 8394  154953.94              1          1               1         70849.47
 5233   88826.07              1          1               1         33759.41

       Exited
 9394       0
 898        1
 2398       0
 5906       0
 2343       0
 ...      ...
 4004       0
 7375       0
 9307       0
 8394       0
 5233       1

 [3000 rows x 13 columns])

In [9]:
cus.isnull().sum() # for finding those data where is no data filled and .sum mean tell me how much null data in those colums

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
cus = pd.get_dummies(cus,columns=['Geography','Gender'],drop_first=True)

In [11]:
x = cus.drop(columns=['Exited'])
y = cus['Exited'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:

from sklearn.preprocessing import StandardScaler

In [15]:
md = StandardScaler()
X_train_scaled = md.fit_transform(X_train)
X_test_scaled = md.transform(X_test)

ValueError: could not convert string to float: 'Mishin'